/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { Mesh } from "three";

export default function Model(): JSX.Element {
  const group = useRef();
  const { materials, ...rest } = useGLTF("/gltf/background/cam_01.gltf");

  const nodes = rest.nodes as {
    [name: string]: Mesh;
  };
  return (
    <group ref={group} dispose={null}>
      <group
        position={[10.81, 34.3, -36.08]}
        rotation={[-Math.PI, -0.7, -Math.PI]}
        scale={[0.8, 0.8, 0.8]}
      >
        <mesh
          geometry={nodes.cam_01PIV.geometry}
          material={nodes.cam_01PIV.material}
          position={[31.74, -27.72, -31.41]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/gltf/background/cam_01.gltf");
