/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { Mesh } from "three";

export default function Model(props) {
  const group = useRef();
  const { materials, ...rest } = useGLTF("/gltf/background/cam_02.gltf");

  const nodes = rest.nodes as {
    [name: string]: Mesh;
  };
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[16.42, 28.38, -30.24]}
        rotation={[-Math.PI, -0.7, -Math.PI]}
        scale={[0.8, 0.8, 0.8]}
      >
        <mesh
          geometry={nodes.cam_02PIV.geometry}
          material={nodes.cam_02PIV.material}
          position={[32.23, -34.69, -22.19]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/gltf/background/cam_02.gltf");
